"""Add created_at to FileData

Revision ID: 06f672ce4c68
Revises: c1666a388913
Create Date: 2023-09-12 22:53:09.187346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f672ce4c68'
down_revision: Union[str, None] = 'c1666a388913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FileData', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FileData', 'created_at')
    # ### end Alembic commands ###
