"""Add file_id to FileData

Revision ID: 8f5f710bf565
Revises: 06f672ce4c68
Create Date: 2023-09-12 23:37:52.619563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5f710bf565'
down_revision: Union[str, None] = '06f672ce4c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FileData', sa.Column('file_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_FileData_file_id'), 'FileData', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_FileData_file_id'), table_name='FileData')
    op.drop_column('FileData', 'file_id')
    # ### end Alembic commands ###
