"""Add product_id to FileData

Revision ID: c1666a388913
Revises: 824b9e4e0984
Create Date: 2023-09-12 22:48:42.680501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1666a388913'
down_revision: Union[str, None] = '824b9e4e0984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FileData', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_FileData_product_id'), 'FileData', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_FileData_product_id'), table_name='FileData')
    op.drop_column('FileData', 'product_id')
    # ### end Alembic commands ###
